"""Admin password

Revision ID: b69802772ad0
Revises: c49c1c1efb73
Create Date: 2024-07-18 16:11:54.212231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69802772ad0'
down_revision: Union[str, None] = 'c49c1c1efb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'hashed_password')
    # ### end Alembic commands ###
