"""Admin JWT

Revision ID: c49c1c1efb73
Revises: 8cc6eb129bb2
Create Date: 2024-07-18 16:11:22.466318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49c1c1efb73'
down_revision: Union[str, None] = '8cc6eb129bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwtadmintoken',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwtadmintoken')
    # ### end Alembic commands ###
